"""Email formatting and sending via Resend API."""

from datetime import datetime
import resend

from .config import RESEND_API_KEY, EMAIL_SENDER, EMAIL_RECIPIENT


def format_award_html(award: dict) -> str:
    """Format a single award as HTML."""
    amount_str = ""
    if award.get("award_amount"):
        amount_str = f"<br><strong>Award:</strong> ${award['award_amount']:,.0f}"

    study_section_str = ""
    if award.get("study_section"):
        study_section_str = f"<br><strong>Study Section:</strong> {award['study_section']}"

    abstract = award.get("abstract", "No abstract available")
    # Truncate long abstracts
    if len(abstract) > 500:
        abstract = abstract[:500] + "..."

    return f"""
    <div style="margin-bottom: 20px; padding: 15px; border: 1px solid #ddd; border-radius: 5px; background-color: #f9f9f9;">
        <h3 style="margin-top: 0; color: #0066cc;">
            <a href="{award.get('nih_reporter_url', '#')}" style="text-decoration: none; color: #0066cc;">
                {award.get('title', 'No title')}
            </a>
        </h3>
        <p style="margin: 5px 0;">
            <strong>PI:</strong> {award.get('pi_name', 'Unknown')}<br>
            <strong>Organization:</strong> {award.get('organization', 'Unknown')}<br>
            <strong>Project #:</strong> {award.get('project_number', 'N/A')}
            {amount_str}
            {study_section_str}
        </p>
        <p style="color: #666; font-size: 0.9em; margin-bottom: 0;">
            {abstract}
        </p>
        <p style="color: #888; font-size: 0.8em; margin-top: 5px;">
            Relevance Score: {award.get('relevance_score', 0)}
        </p>
    </div>
    """


def format_nofo_html(nofo: dict) -> str:
    """Format a single NOFO as HTML."""
    summary = nofo.get("summary", "No summary available")
    # Truncate long summaries
    if len(summary) > 400:
        summary = summary[:400] + "..."

    return f"""
    <div style="margin-bottom: 20px; padding: 15px; border: 1px solid #ddd; border-radius: 5px; background-color: #fff9f0;">
        <h3 style="margin-top: 0; color: #cc6600;">
            <a href="{nofo.get('link', '#')}" style="text-decoration: none; color: #cc6600;">
                {nofo.get('title', 'No title')}
            </a>
        </h3>
        <p style="margin: 5px 0;">
            <strong>Published:</strong> {nofo.get('published', 'Unknown')}
        </p>
        <p style="color: #666; font-size: 0.9em; margin-bottom: 0;">
            {summary}
        </p>
        <p style="color: #888; font-size: 0.8em; margin-top: 5px;">
            Relevance Score: {nofo.get('relevance_score', 0)}
        </p>
    </div>
    """


def build_digest_html(awards: list[dict], nofos: list[dict]) -> str:
    """Build the complete HTML email digest."""
    date_str = datetime.now().strftime("%B %d, %Y")

    awards_html = ""
    if awards:
        awards_html = "".join(format_award_html(a) for a in awards)
    else:
        awards_html = "<p>No new R01 awards matching your keywords this week.</p>"

    nofos_html = ""
    if nofos:
        nofos_html = "".join(format_nofo_html(n) for n in nofos)
    else:
        nofos_html = "<p>No new funding opportunities matching your keywords this week.</p>"

    return f"""
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="utf-8">
        <style>
            body {{
                font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;
                line-height: 1.6;
                color: #333;
                max-width: 800px;
                margin: 0 auto;
                padding: 20px;
            }}
            h1 {{
                color: #003366;
                border-bottom: 2px solid #003366;
                padding-bottom: 10px;
            }}
            h2 {{
                color: #0066cc;
                margin-top: 30px;
            }}
            .summary {{
                background-color: #e6f2ff;
                padding: 15px;
                border-radius: 5px;
                margin-bottom: 20px;
            }}
        </style>
    </head>
    <body>
        <h1>NIH Grant Digest - {date_str}</h1>

        <div class="summary">
            <strong>This Week's Summary:</strong><br>
            New R01 Awards: {len(awards)}<br>
            New Funding Opportunities: {len(nofos)}
        </div>

        <h2>New R01 Awards</h2>
        {awards_html}

        <h2>New Funding Opportunities (NOFOs)</h2>
        {nofos_html}

        <hr style="margin-top: 30px;">
        <p style="color: #888; font-size: 0.8em;">
            This digest was automatically generated by NIH Grant Scraper.<br>
            Keywords: aging, mitochondria, immunology, cardiovascular, neuroinflammation, and related topics.
        </p>
    </body>
    </html>
    """


def build_plain_text(awards: list[dict], nofos: list[dict]) -> str:
    """Build plain text version of the digest."""
    date_str = datetime.now().strftime("%B %d, %Y")

    lines = [
        f"NIH Grant Digest - {date_str}",
        "=" * 50,
        "",
        f"This Week's Summary:",
        f"  New R01 Awards: {len(awards)}",
        f"  New Funding Opportunities: {len(nofos)}",
        "",
        "NEW R01 AWARDS",
        "-" * 30,
    ]

    if awards:
        for a in awards:
            lines.append(f"\n{a.get('title', 'No title')}")
            lines.append(f"  PI: {a.get('pi_name', 'Unknown')}")
            lines.append(f"  Org: {a.get('organization', 'Unknown')}")
            lines.append(f"  URL: {a.get('nih_reporter_url', 'N/A')}")
    else:
        lines.append("\nNo new R01 awards matching your keywords this week.")

    lines.extend([
        "",
        "NEW FUNDING OPPORTUNITIES",
        "-" * 30,
    ])

    if nofos:
        for n in nofos:
            lines.append(f"\n{n.get('title', 'No title')}")
            lines.append(f"  Published: {n.get('published', 'Unknown')}")
            lines.append(f"  URL: {n.get('link', 'N/A')}")
    else:
        lines.append("\nNo new funding opportunities matching your keywords this week.")

    return "\n".join(lines)


def send_digest(awards: list[dict], nofos: list[dict]) -> bool:
    """Send the weekly digest email via Resend."""
    if not RESEND_API_KEY:
        print("Error: RESEND_API_KEY not configured")
        return False

    if not EMAIL_SENDER or not EMAIL_RECIPIENT:
        print("Error: EMAIL_SENDER or EMAIL_RECIPIENT not configured")
        return False

    resend.api_key = RESEND_API_KEY

    date_str = datetime.now().strftime("%B %d, %Y")
    subject = f"NIH Grant Digest - {date_str}"

    html_content = build_digest_html(awards, nofos)

    try:
        params = {
            "from": EMAIL_SENDER,
            "to": [EMAIL_RECIPIENT],
            "subject": subject,
            "html": html_content,
        }

        response = resend.Emails.send(params)
        print(f"Email sent successfully. ID: {response.get('id', 'unknown')}")
        return True
    except Exception as e:
        print(f"Error sending email: {e}")
        return False
